name: build

on:
  workflow_dispatch:
  schedule:
    - cron: '17 1 * * *'

jobs:
  build_humble:
    runs-on: ubuntu-20.04
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: focal
          ROS_DISTRO: galactic
          REPOS_FILE: https://raw.githubusercontent.com/griswaldbrooks/external_packages/main/upstream.repos
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
